name: automate terraform

on:
  push:
    branches:
      - feature/*

env:
  ENVIRONMENT: "develop"

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Configure AWS Credentials
        id: config_aws_creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: us-east-1 

      - name: create resources
        id: resources
        run: |
          chmod +x ./create_resources.sh
          ./create_resources.sh
        shell: bash
        working-directory: .github/jobs      

      - name: terraform_init 
        id: init
        run: |
          export BUCKET_NAME="terralab-${ENVIRONMENT}-test-01"
          export DYNAMODB_TABLE="dynamodb-table-${ENVIRONMENT}-test"
          export AWS_REGION="us-east-1"
          terraform init \
          -backend-config="bucket=${BUCKET_NAME}" \
          -backend-config="region=${AWS_REGION}" \
          -backend-config="key=Terraform-tfstate" \
          -backend-config="dynamodb_table=${DYNAMODB_TABLE}"
            
      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan

      - name: Apply 
        run: |
          terraform apply -auto-approve tfplan
