name: Hello-world

on:
    push:
        branches:
            - feature/*
    workflow_dispatch:

jobs:
    Hello_World:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Echo del mensaje
              id: echo-mensaje
              run: |
               echo ¡Hello World!
            - name: Dime la fecha
              run: date
            - name: correr script
              id: script-hello
              run: ls -l .github/jobs/hello.sh
                ./hello.sh
              shell: bash
              working-directory: .github/jobs
            - name: Configure AWS Credentials
              id: config_aws_creds
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                aws-region: us-east-2