name: Deployment Pipeline

on:
    push:
        branches:
            -'feature/*'

jobs: 
    deploy:
        runs-on: ubuntu.latest
        steps: 
            - uses: actions/checkout@v3
            - name: Echo del mensaje
              run: |
               echo "Hello World!"
            - name: Dime la fecha
              run: date
            - run: ls -l 


